name: Deregister Old AMIs

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-central-1'
      keep_history:
        description: 'Number of recent AMIs to keep per app'
        required: false
        default: '3'
      limit:
        description: 'Limit on number of app groups to process'
        required: false
        default: '0'
      toolkit_version:
        description: 'Version of the toolkit for script download'
        required: false
        default: 'default'
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 03:00 UTC

env:
  ROLE: "arn:aws:iam::992382682634:role/aws-mastermind-workflow-role"
  REGION: ${{ github.event.inputs.region || 'eu-central-1' }}
  TOOLKIT_VERSION: ${{ github.event.inputs.toolkit_version || 'default' }}
  KEEP_HISTORY: ${{ github.event.inputs.keep_history || '3' }}
  LIMIT: ${{ github.event.inputs.limit || '0' }}
  USES: "inqwise/ansible-automation-toolkit/.github/workflows/ami-clean-old-origin.yml@${{ env.TOOLKIT_VERSION }}"

jobs:
  deregister_old_amis:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-clean-old-origin.yml@default
    with:
      ROLE: ${{ env.ROLE }}
      TOOLKIT_VERSION: ${{ env.TOOLKIT_VERSION }}
      REGION: ${{ env.REGION }}
      KEEP_HISTORY: ${{ env.KEEP_HISTORY }}
      LIMIT: ${{ env.LIMIT }}