name: AMI Copy Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: true
        default: 'default'
      REGION:
        description: 'AWS region for copy to (e.g., us-west-2)'
        required: true
        default: 'il-central-1'
      SOURCE_REGION:
        description: 'AWS region from AMIs copied (e.g., eu-central-1)'
        required: true
        default: 'eu-central-1'
      SOURCE_ACCOUNT_ID:
        description: 'AWS account ID from AMIs copied (optional)'
        required: false
        default: ''

env:
  ROLE: "arn:aws:iam::992382682634:role/aws-mastermind-workflow-role"
  TOOLKIT_VERSION: ${{ github.event.inputs.TOOLKIT_VERSION || 'default' }}
  REGION: ${{ github.event.inputs.REGION || 'il-central-1' }}
  SOURCE_REGION: ${{ github.event.inputs.SOURCE_REGION || 'eu-central-1' }}
  SOURCE_ACCOUNT_ID: ${{ github.event.inputs.SOURCE_ACCOUNT_ID || '' }}

jobs:
  ami_copy:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-copy-shared.yml@${{ env.TOOLKIT_VERSION }}
    with:
      ROLE: ${{ env.ROLE }}
      TOOLKIT_VERSION: ${{ env.TOOLKIT_VERSION }}
      REGION: ${{ env.REGION }}
      SOURCE_REGION: ${{ env.SOURCE_REGION }}
      SOURCE_ACCOUNT_ID: ${{ env.SOURCE_ACCOUNT_ID }}