name: AMI Assign Template Workflow

on:
  schedule:
    - cron: '10,20 0 * * *'  # Runs daily at 00:10 and 00:20 UTC
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: false
        default: 'default'
      REGION:
        description: 'AWS region for assignment (e.g., il-central-1)'
        required: false
        default: 'il-central-1'
      MAKE_DEFAULT_VERSION:
        description: 'Make Default Version (true/false)'
        required: false
        default: 'true'

env:
  ROLE: "arn:aws:iam::992382682634:role/aws-mastermind-workflow-role"
  TOOLKIT_VERSION: ${{ inputs.TOOLKIT_VERSION || 'default' }}
  REGION: ${{ inputs.REGION || 'il-central-1' }}
  MAKE_DEFAULT_VERSION: ${{ inputs.MAKE_DEFAULT_VERSION || 'true' }}

jobs:
  ami_assign:
    uses: inqwise/ansible-automation-toolkit/.github/workflows/ami-assign-template.yml@defult
    with:
      ROLE: ${{ ROLE }}
      TOOLKIT_VERSION: ${{ TOOLKIT_VERSION }}
      REGION: ${{ REGION }}
      MAKE_DEFAULT_VERSION: ${{ MAKE_DEFAULT_VERSION }}