name: AMI Copy Workflow

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  workflow_dispatch:
    inputs:
      TOOLKIT_VERSION:
        description: 'Version of the Ansible Automation Toolkit'
        required: true
        default: 'default'
      REGION:
        description: 'AWS region for copy to (e.g., us-west-2)'
        required: true
        default: 'il-central-1'
      SOURCE_REGION:
        description: 'AWS region from AMIs copied (e.g., eu-central-1)'
        required: true
        default: 'eu-central-1'
      SOURCE_ACCOUNT_ID:
        description: 'AWS account ID from AMIs copied (optional)'
        required: false
        default: ''

env:
  JOB_TOOLKIT_VERSION: 'default'
  JOB_REGION: 'il-central-1'
  JOB_SOURCE_REGION: ''
  JOB_SOURCE_ACCOUNT_ID: ''

jobs:
  ami_copy:
    uses: "inqwise/ansible-automation-toolkit/.github/workflows/goldenimage-workflow.yml@${{ inputs.TOOLKIT_VERSION || JOB_TOOLKIT_VERSION }}"
    with:
      ROLE: "arn:aws:iam::992382682634:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: "${{ inputs.TOOLKIT_VERSION || JOB_TOOLKIT_VERSION }}"
      REGION: "${{ inputs.REGION || JOB_REGION }}"
      SOURCE_REGION: "${{ inputs.SOURCE_REGION || JOB_SOURCE_REGION }}"
      SOURCE_ACCOUNT_ID: "${{ inputs.SOURCE_ACCOUNT_ID || JOB_SOURCE_ACCOUNT_ID }}"