name: Deregister Old AMIs

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-central-1'
      keep_history:
        description: 'Number of recent AMIs to keep per app'
        required: false
        default: '3'
      limit:
        description: 'Limit on number of app groups to process'
        required: false
        default: '0'
      toolkit_version:
        description: 'Version of the toolkit for script download'
        required: false
        default: 'default'
  schedule:
    - cron: '0 3 * * *' # Runs daily at 03:00 UTC; adjust as needed

env:
  JOB_REGION: 'eu-central-1'
  JOB_TOOLKIT_VERSION: 'default'
  JOB_KEEP_HISTORY: 3
  JOB_LIMIT: 0

jobs:
  deregister_old_amis:
    uses: "inqwise/ansible-automation-toolkit/.github/workflows/goldenimage-workflow.yml@${{ inputs.TOOLKIT_VERSION || JOB_TOOLKIT_VERSION }}"
    with:
      ROLE: "arn:aws:iam::992382682634:role/aws-mastermind-workflow-role"
      TOOLKIT_VERSION: "${{ inputs.TOOLKIT_VERSION || JOB_TOOLKIT_VERSION }}"
      REGION: "${{ inputs.REGION || JOB_REGION }}"